### ISSUE TITLE
pycuda on Windows

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#16]
[Installing pycuda on the Windows GitHub runner via pip fails](https://github.com/neuro-conda/neuro-conda/actions/runs/4303602993/jobs/7503537040) due to the missing/misconfigured compiler. Installing via conda works though. @pantaray, Why did you actually move pycuda from conda to pip?

**Comment by pantaray** [comment]
Ups, sorry! I moved it just to be able to use pip's conditional install flags (`platform_system`, `platform_machine` etc.). I was hoping that pycuda would provide pip-wheels for Windows...
