### ISSUE TITLE
Include an editor?

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#2]
Should we include Spyder/Jupyter/... ?

**Comment by joschaschmiedt** [comment]
A flag for the "installer" indicating whether an editor such as Spyder should be installed may be useful.

**Comment by pantaray** [comment]
> A flag for the "installer" indicating whether an editor such as Spyder should be installed may be useful.

Yes, good idea!

**Comment by pantaray** [comment]
> Should we include Spyder/Jupyter/... ?

I think Jupyter(lab) is almost obligatory nowadays with so many people doing their analyses in notebooks.

**Comment by pantaray** [comment]
> > A flag for the "installer" indicating whether an editor such as Spyder should be installed may be useful.
> 
> 
> 
> Yes, good idea!
> 
> 

How about an environment variable? Then users could do something like (on *nix systems at least):
```
export ncEditor=1
/bin/bash -c "(curl ...)"
```
And inside is the install script we then check whether `ncEditor` is defined.

**Comment by joschaschmiedt** [comment]
I like that! The version could also be encoded in an env variable.
