### ISSUE TITLE
Add neuroimaging packages

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#20]
Follow-up of #3 

- [x] nipype
- [x] dipy
- [ ] mindboogle
- [x] nibabel
- [x] napari-nibabel
- [ ] scitran SDM
- [ ] nipy
- [x] nibabel
- [ ] Scitran SDM
- [ ] nipy
- [x] nitime
- [x] popeye
- [x] nilearn
- [ ] pymvpa
- [x] mne
- [x] mnelab
- [x] mne-realtime
- [x] mne-rsa
- [x] mne-nirs
- [x] mne-icalabel
- [x] mne-connectivity
- [x] mne-features
- [x] mne-bids
- [x] mne-bids-pipeline
- [x] mne-ari
- [ ] niwidgets
- [x] pybids
- [ ] nistats
- [x] imageio
- [x] pydicom
- [x] deid
- [x] intensity-normalization

**Comment by pantaray** [comment]
I've included a first batch of neuroimaging packages in the environment. Some hiccups:

- `mindboogle` is not packaged per se but only provides a [Docker image](https://mindboggle.readthedocs.io/en/latest/#installation)
- `scitran` does not provide a package, only a REST API
- `nipy`: problematic on macOS and Windows. The conda package only supports Python 3.8, pip does not provide a wheel and needs to build nipy against BLAS/LAPACK which currently crashes on both macOS and Windows. 
- `pymvpa`: from the docs "...Python 3.X should work too, but none of the core developers are using it in production (yet), hence it should be considered as less tested...."
- `niwidgets`: depends on `scikit-learn` < 0.21 (we're using 1.2.1)
- `nistats`: dependency conflict with `nibabel`/`intensity-normalization`

I think not providing `nipy` on all platforms might be the biggest omission here. However, that still strongly depends the actual application. Do we want to proceed with `nipy` only on Linux and see if and how many macOS/Windows users actually need it? Tests with the current env file are passing: https://github.com/neuro-conda/neuro-conda/actions/runs/4344547143

**Comment by joschaschmiedt** [comment]
Thanks! Supporting Linux only is better than not at all, so I think that's fine. About the other issues, there's not much we can do about that, right?

See also my comments over at #29

**Comment by pantaray** [comment]
Yes, aside from actively patching/rewriting things I'm afraid we can't do much here.
