### ISSUE TITLE
Uninstaller need fix for linux

### ISSUE THREAD

**Issue by davrot** [neuro-conda/neuro-conda#28]
Please do this on uninstaller.sh 
```
#if [ -z "${BASH_VERSION:-}" ]
#then
#  posix_abort "Bash is required to interpret this script."
#fi
```

**Comment by joschaschmiedt** [comment]
Thanks for the report. Which shell are you using?

**Comment by davrot** [comment]
The same like the system I send you the account for... 

[admin@fedora ~]$ bash --version
GNU bash, Version 5.2.2(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
Lizenz GPLv3+: GNU GPL Version 3 oder jünger <http://gnu.org/licenses/gpl.html>

[root@fedora admin]# lsb_release  -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 37 (Thirty Seven)
Release:	37
Codename:	ThirtySeven

**Comment by davrot** [comment]
Sorry I meant this one:
# if [[ -n "${POSIXLY_CORRECT+1}" ]]
# then
#   posix_abort 'Bash must not run in POSIX mode. Please unset POSIXLY_CORRECT and try again.'
# fi

**Comment by joschaschmiedt** [comment]
Ah, I missed it in the uninstaller. @pantaray, do you know why `POSIXLY_CORRECT` must not be set in the brew installer? It doesn't seem to affect our tests on macOS and Ubuntu. 

@davrot, I removed it now, please test.

**Comment by davrot** [comment]
Works now

**Comment by pantaray** [comment]
> Ah, I missed it in the uninstaller. @pantaray, do you know why `POSIXLY_CORRECT` must not be set in the brew installer?

Not really, to be honest. I assumed it was there to ensure a recent enough bash version so that the ANSI text formatting works. But apparently that's not an issue. I think we can remove the check.
