### ISSUE TITLE
Initially included packages

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#3]
Here we collect the neuroscience-related packages that we initially attempt to support:

#### Electrophysiology
- [x] neo
- [x] elephant
- [ ] #24
- [x] mne-python
- [x] esi-syncopy
- [x] esi-acme
- [x] dask
- [x] nwb
- [ ] #23
- [x] neurodsp
- [ ] ~~#15~~
- [x] SpikeInterface
- [ ] #21
- [ ] #22
- [x] nixio
- [x] fooof
- [x] bycycle

#### Neuroimaging
- [ ] nipype
- [ ] dipy
- [ ] mindboogle
- [ ] nibabel
- [ ] napari-nibabel
- [ ] scitran SDM
- [ ] nipy
- [ ] nibabel
- [ ] Scitran SDM
- [ ] nipy
- [ ] nitime
- [ ] popeye
- [ ] nilearn
- [ ] pymvpa
- [x] mne
- [ ] mnelab
- [ ] mne-realtime
- [ ] mne-rsa
- [ ] mne-nirs
- [ ] mne-icalabel
- [ ] mne-connectivity
- [ ] mne-features
- [ ] mne-bids
- [ ] mne-bids-pipeline
- [ ] mne-ari
- [ ] niwidgets
- [ ] pybids
- [ ] nistats
- [ ] imageio
- [ ] pydicom
- [ ] deid
- [ ] intensity-normalization

#### Implicit, useful dependencies 
- numpy
- scipy
- matplotlib
- scikit-learn
- jupyter
- hdf5

#### Some further  candidates
- [ ] #25
- [ ] #26

**Comment by joschaschmiedt** [comment]
Some further  candidates
- [ ] [ReproMan](https://reproman.readthedocs.io)
- [ ] [Neurodocker](https://www.repronim.org/neurodocker)

**Comment by joschaschmiedt** [comment]
> Unless you have any objections, I think we might want to initially focus on the non-ML Python-only packages in the first list above.

Agreed.

**Comment by joschaschmiedt** [comment]
@pantaray, would you mind to try out how difficult adding some of the neuroimaging packages is?

**Comment by joschaschmiedt** [comment]
Suggestions from @davrot
- tqdm
- argh
- pywavelets
- scikit-learn
- ( ipympl )
- ( opencv-python )
- ( scikit-image )

**Comment by davrot** [comment]
Status unclear:
mindboogle (needs docker container?)
pymvpa
intensity-normalization

Dead project:
scitran SDM
https://github.com/scitran/sdm

broken ?
niwidgets

version problem:
pigar


[neuro-conda-latest.yml.txt](https://github.com/neuro-conda/neuro-conda/files/10884340/neuro-conda-latest.yml.txt)
[log_03032023b.txt](https://github.com/neuro-conda/neuro-conda/files/10884342/log_03032023b.txt)
