### ISSUE TITLE
Provide pure pip environments

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#47]
As conda can sometimes be problematic (e.g. using it with `pyinstaller` does not work) I think it may make sense to at least try how far we can get with simple `requirements.txt` for each neuro-conda version. 

This could eventually also end up in a pypi meta-package.

**Comment by joschaschmiedt** [comment]
We may have to consider renaming the project ;-)

**Comment by pantaray** [comment]
Good idea! I think it's definitely worth a shot. Not sure how far we'll get with Apple Silicon, but it should be reasonably quick to find out ;)

**Comment by joschaschmiedt** [comment]
Except `eelbrain`, installing via pip seems to work fine (on Windows).

```powershell
PS C:\Code\envs> python -m venv neuro-conda-2023b
PS C:\Code\envs> .\neuro-conda-2023b\Scripts\Activate.ps1
(neuro-conda-2023b) PS C:\Code\envs> pip install uv
Collecting uv
  Using cached uv-0.2.2-py3-none-win_amd64.whl (10.8 MB)
Installing collected packages: uv
Successfully installed uv-0.2.2

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
(neuro-conda-2023b) PS C:\Code\envs> uv pip install -r C:\Code\neuro-conda\envs\neuro-conda-2023b.txt
Resolved 297 packages in 580ms
Downloaded 1 package in 45ms
Installed 296 packages in 4.67s
(neuro-conda-2023b) PS C:\Code\envs> pip freeze > neuro-conda-2023b.lock.txt
```
Would you mind testing the lock file on macOS, @pantaray? See the https://github.com/neuro-conda/neuro-conda/pull/48

**Comment by pantaray** [comment]
Yupp, of course! Probably won't get to it right now, I'll try tomorrow or Monday if that's okay

**Comment by pantaray** [comment]
Sorry, I'm pretty slow here, but I managed to do some testing. Under Linux I got the following error when trying to install `mpi4py`:
```
_configtest.c:2:10: fatal error: mpi.h: No such file or directory
    2 | #include <mpi.h>
      |          ^~~~~~~
compilation terminated.
error: Cannot compile MPI programs. Check your configuration!!!
---
  Caused by: This error likely indicates that you need to install a library that provides "mpi.h" for mpi4py==3.1.6
```
In general, I see the problem, that installing via pip/uv only works if Python is already present on the system. I think at least in Windows  that's not the case (unless recent Win11 versions come with Python pre-installed?), macOS ships with Python but it's heavily customized and pretty old - I'm not sure we want to rely on it. If we have to install Python from scratch, then we're back to conda, I'm afraid...

How about providing neuro-conda pip-env files in addition to the conda ymls? That way, we can still offer the possibility to install Python + neuro-conda from scratch but make it possible for users with existing Python installations to use a pure pip-based environment if they prefer.

**Comment by joschaschmiedt** [comment]
Don't worry, I'm even slower. I agree that maintaining the requirements.txt for all supported systems is probably not feasible. My main gripe with conda is that pyinstaller often doesn't work, but that's a special case anyway. 

I think I'll add the requirements.txt if I find the time, but we don't have to support it for every release.
