### ISSUE TITLE
mamba: error: unrecognized arguments: --force

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#49]
Something seems to have changed about the `--force` argument of `mamba` causing an error during our installation script. See e.g. https://github.com/neuro-conda/neuro-conda/actions/runs/9209582797/job/25334525737?pr=48

**Comment by pantaray** [comment]
Recent versions of conda use `libmamba` as default solver - maybe we should get rid of mamba at all? The official recommendation is to not use mamba with existing conda installations but rely on [miniforge](https://mamba.readthedocs.io/en/latest/installation/mamba-installation.html) instead.

**Comment by joschaschmiedt** [comment]
Interesting. I suppose that warrants switching to miniforge. Rename the project to neuro-forge? ;-)
