### ISSUE TITLE
Write an "installer" for Linux

### ISSUE THREAD

**Issue by joschaschmiedt** [neuro-conda/neuro-conda#6]

**Comment by pantaray** [comment]
Working on it - I think this goes hand in hand with #7

**Comment by pantaray** [comment]
Pretty much done with #7 But should be included in our test matrix

**Comment by davrot** [comment]
[neuro-conda-latest_linux.yml.txt](https://github.com/neuro-conda/neuro-conda/files/10881335/neuro-conda-latest_linux.yml.txt)

**Comment by davrot** [comment]
[install.sh.txt](https://github.com/neuro-conda/neuro-conda/files/10881547/install.sh.txt)
[uninstall.sh.txt](https://github.com/neuro-conda/neuro-conda/files/10881549/uninstall.sh.txt)

**Comment by davrot** [comment]
Done this:
## Check if script is run in POSIX mode
#if [[ -n "${POSIXLY_CORRECT+1}" ]]
#then
#  posix_abort 'Bash must not run in POSIX mode. Please unset POSIXLY_CORRECT and try again.'
#fi

and this:

if [[ "${OS}" == "Linux" ]]; then
  info "Using Linux config..."
  NeuroCondaLatestUrl="https://raw.githubusercontent.com/neuro-conda/neuro-conda/main/envs/neuro-conda-latest_linux.yml"
else
  info "Using Default config..."
  NeuroCondaLatestUrl="https://raw.githubusercontent.com/neuro-conda/neuro-conda/main/envs/neuro-conda-latest.yml"
fi

if curl --output /dev/null --silent --head --fail "$NeuroCondaLatestUrl"; then 
  info "$NeuroCondaLatestUrl exits"
else
  error "$NeuroCondaLatestUrl does not exits!!!"
fi

**Comment by davrot** [comment]
@joschaschmiedt You need to figure out what it breaks on your end. :-)

**Comment by joschaschmiedt** [comment]
Thanks, @davrot, I included your suggestions in #19. The platform-specific installation of the ML packages is now handled via Pip's `platform_architecture` and `platform_system` flags (like [this](https://github.com/neuro-conda/neuro-conda/blob/abedd676480cca6b2ac3028c7d6d38b4437c7aac/envs/neuro-conda-latest.yml#L40)).
