### ISSUE TITLE
latest environment

### ISSUE THREAD

**Issue by pantaray** [neuro-conda/neuro-conda#8]
Do we want the `*-latest.yml` env file to be an actual file or just a symlink to the most recent YAML (currently 2023a)?

**Comment by joschaschmiedt** [comment]
If a symlink works on Windows as well, a symlink is probably better. Haven't tested it yet though.

**Comment by pantaray** [comment]
Ah yes, Windows, of course. Sorry, my bad.

**Comment by joschaschmiedt** [comment]
I'm closing this, the symlink doesn't really work on Windows. Also, we can use the `neuro-conda-latest.yml` for development and only create the versioned YAML files on release.
